from .lib.type cimport *
from .lib.file cimport *
from .lib.poll cimport *
from .lib.statx cimport *
from .lib.futex cimport *
from .lib.socket cimport *
from .lib.io_uring cimport *


# fsync flags
IORING_FSYNC_DATASYNC = __IORING_FSYNC_DATASYNC

# sqe.flags
IOSQE_FIXED_FILE = __IOSQE_FIXED_FILE
IOSQE_IO_DRAIN = __IOSQE_IO_DRAIN
IOSQE_IO_LINK = __IOSQE_IO_LINK
IOSQE_IO_HARDLINK = __IOSQE_IO_HARDLINK
IOSQE_ASYNC = __IOSQE_ASYNC
IOSQE_BUFFER_SELECT = __IOSQE_BUFFER_SELECT
IOSQE_CQE_SKIP_SUCCESS = __IOSQE_CQE_SKIP_SUCCESS

IORING_URING_CMD_FIXED = __IORING_URING_CMD_FIXED

IORING_TIMEOUT_ABS = __IORING_TIMEOUT_ABS
IORING_TIMEOUT_UPDATE = __IORING_TIMEOUT_UPDATE
IORING_TIMEOUT_BOOTTIME = __IORING_TIMEOUT_BOOTTIME
IORING_TIMEOUT_REALTIME = __IORING_TIMEOUT_REALTIME
IORING_LINK_TIMEOUT_UPDATE = __IORING_LINK_TIMEOUT_UPDATE
IORING_TIMEOUT_ETIME_SUCCESS = __IORING_TIMEOUT_ETIME_SUCCESS
IORING_TIMEOUT_MULTISHOT = __IORING_TIMEOUT_MULTISHOT
IORING_TIMEOUT_CLOCK_MASK = __IORING_TIMEOUT_CLOCK_MASK
IORING_TIMEOUT_UPDATE_MASK = __IORING_TIMEOUT_UPDATE_MASK

SPLICE_F_FD_IN_FIXED = __SPLICE_F_FD_IN_FIXED

IORING_POLL_ADD_MULTI = __IORING_POLL_ADD_MULTI
IORING_POLL_UPDATE_EVENTS = __IORING_POLL_UPDATE_EVENTS
IORING_POLL_UPDATE_USER_DATA = __IORING_POLL_UPDATE_USER_DATA
IORING_POLL_ADD_LEVEL = __IORING_POLL_ADD_LEVEL

IORING_ASYNC_CANCEL_ALL = __IORING_ASYNC_CANCEL_ALL
IORING_ASYNC_CANCEL_FD = __IORING_ASYNC_CANCEL_FD
IORING_ASYNC_CANCEL_ANY = __IORING_ASYNC_CANCEL_ANY
IORING_ASYNC_CANCEL_FD_FIXED = __IORING_ASYNC_CANCEL_FD_FIXED

IORING_RECVSEND_POLL_FIRST = __IORING_RECVSEND_POLL_FIRST
IORING_RECV_MULTISHOT = __IORING_RECV_MULTISHOT
IORING_RECVSEND_FIXED_BUF = __IORING_RECVSEND_FIXED_BUF
IORING_SEND_ZC_REPORT_USAGE = __IORING_SEND_ZC_REPORT_USAGE

IORING_NOTIF_USAGE_ZC_COPIED = __IORING_NOTIF_USAGE_ZC_COPIED

IORING_ACCEPT_MULTISHOT = __IORING_ACCEPT_MULTISHOT

cpdef enum io_uring_msg_op:
    IORING_MSG_DATA = __IORING_MSG_DATA
    IORING_MSG_SEND_FD = __IORING_MSG_SEND_FD

IORING_MSG_RING_CQE_SKIP = __IORING_MSG_RING_CQE_SKIP
IORING_MSG_RING_FLAGS_PASS = __IORING_MSG_RING_FLAGS_PASS
IORING_FIXED_FD_NO_CLOEXEC = __IORING_FIXED_FD_NO_CLOEXEC

IORING_CQE_F_BUFFER = __IORING_CQE_F_BUFFER
IORING_CQE_F_MORE = __IORING_CQE_F_MORE
IORING_CQE_F_SOCK_NONEMPTY = __IORING_CQE_F_SOCK_NONEMPTY
IORING_CQE_F_NOTIF = __IORING_CQE_F_NOTIF

cpdef enum io_uring_cqe_op:
    IORING_CQE_BUFFER_SHIFT = __IORING_CQE_BUFFER_SHIFT

IORING_OFF_SQ_RING = __IORING_OFF_SQ_RING
IORING_OFF_CQ_RING = __IORING_OFF_CQ_RING
IORING_OFF_SQES = __IORING_OFF_SQES
IORING_OFF_PBUF_RING = __IORING_OFF_PBUF_RING
IORING_OFF_PBUF_SHIFT = __IORING_OFF_PBUF_SHIFT
IORING_OFF_MMAP_MASK = __IORING_OFF_MMAP_MASK

IORING_SQ_NEED_WAKEUP = __IORING_SQ_NEED_WAKEUP
IORING_SQ_CQ_OVERFLOW = __IORING_SQ_CQ_OVERFLOW
IORING_SQ_TASKRUN = __IORING_SQ_TASKRUN

IORING_CQ_EVENTFD_DISABLED = __IORING_CQ_EVENTFD_DISABLED

IORING_FEAT_SINGLE_MMAP = __IORING_FEAT_SINGLE_MMAP
IORING_FEAT_NODROP = __IORING_FEAT_NODROP
IORING_FEAT_SUBMIT_STABLE = __IORING_FEAT_SUBMIT_STABLE
IORING_FEAT_RW_CUR_POS = __IORING_FEAT_RW_CUR_POS
IORING_FEAT_CUR_PERSONALITY = __IORING_FEAT_CUR_PERSONALITY
IORING_FEAT_FAST_POLL = __IORING_FEAT_FAST_POLL
IORING_FEAT_POLL_32BITS = __IORING_FEAT_POLL_32BITS
IORING_FEAT_SQPOLL_NONFIXED = __IORING_FEAT_SQPOLL_NONFIXED
IORING_FEAT_EXT_ARG = __IORING_FEAT_EXT_ARG
IORING_FEAT_NATIVE_WORKERS = __IORING_FEAT_NATIVE_WORKERS
IORING_FEAT_RSRC_TAGS = __IORING_FEAT_RSRC_TAGS
IORING_FEAT_CQE_SKIP = __IORING_FEAT_CQE_SKIP
IORING_FEAT_LINKED_FILE = __IORING_FEAT_LINKED_FILE
IORING_FEAT_REG_REG_RING = __IORING_FEAT_REG_REG_RING

cpdef enum io_uring_wq_op:
    IO_WQ_BOUND = __IO_WQ_BOUND
    IO_WQ_UNBOUND = __IO_WQ_UNBOUND

IORING_RSRC_REGISTER_SPARSE = __IORING_RSRC_REGISTER_SPARSE

IORING_REGISTER_FILES_SKIP = __IORING_REGISTER_FILES_SKIP
IO_URING_OP_SUPPORTED = __IO_URING_OP_SUPPORTED

cpdef enum io_uring_buf_op:
    IOU_PBUF_RING_MMAP = __IOU_PBUF_RING_MMAP

cpdef enum io_uring_restriction_op:
    IORING_RESTRICTION_REGISTER_OP = __IORING_RESTRICTION_REGISTER_OP
    IORING_RESTRICTION_SQE_OP = __IORING_RESTRICTION_SQE_OP
    IORING_RESTRICTION_SQE_FLAGS_ALLOWED = __IORING_RESTRICTION_SQE_FLAGS_ALLOWED
    IORING_RESTRICTION_SQE_FLAGS_REQUIRED = __IORING_RESTRICTION_SQE_FLAGS_REQUIRED
    IORING_RESTRICTION_LAST = __IORING_RESTRICTION_LAST
