const c = @import("c.zig").c;
const oz = @import("PyOZ");
const std = @import("std");

// Liburing
// --------
// miscellaneous
pub const IO_URING_VERSION_MAJOR = c.IO_URING_VERSION_MAJOR;
pub const IO_URING_VERSION_MINOR = c.IO_URING_VERSION_MINOR;

pub const IOV_MAX = std.posix.IOV_MAX;
// liburing.h START >>>
pub const LIBURING_UDATA_TIMEOUT = c.LIBURING_UDATA_TIMEOUT;
// Tell the app the have the 64-bit variants of the get/set userdata
pub const LIBURING_HAVE_DATA64 = c.LIBURING_HAVE_DATA64;
// liburing.h END <<<

// io_uring.h START >>>
pub const IORING_RW_ATTR_FLAG_PI = c.IORING_RW_ATTR_FLAG_PI;
pub const IORING_FILE_INDEX_ALLOC = c.IORING_FILE_INDEX_ALLOC;

// sqe.flags
pub const IOSQE_FIXED_FILE = c.IOSQE_FIXED_FILE;
pub const IOSQE_IO_DRAIN = c.IOSQE_IO_DRAIN;
pub const IOSQE_IO_LINK = c.IOSQE_IO_LINK;
pub const IOSQE_IO_HARDLINK = c.IOSQE_IO_HARDLINK;
pub const IOSQE_ASYNC = c.IOSQE_ASYNC;
pub const IOSQE_BUFFER_SELECT = c.IOSQE_BUFFER_SELECT;
pub const IOSQE_CQE_SKIP_SUCCESS = c.IOSQE_CQE_SKIP_SUCCESS;

// io_uring_setup() flags
pub const IORING_SETUP_IOPOLL = c.IORING_SETUP_IOPOLL;
pub const IORING_SETUP_SQPOLL = c.IORING_SETUP_SQPOLL;
pub const IORING_SETUP_SQ_AFF = c.IORING_SETUP_SQ_AFF;
pub const IORING_SETUP_CQSIZE = c.IORING_SETUP_CQSIZE;
pub const IORING_SETUP_CLAMP = c.IORING_SETUP_CLAMP;
pub const IORING_SETUP_ATTACH_WQ = c.IORING_SETUP_ATTACH_WQ;
pub const IORING_SETUP_R_DISABLED = c.IORING_SETUP_R_DISABLED;
pub const IORING_SETUP_SUBMIT_ALL = c.IORING_SETUP_SUBMIT_ALL;

pub const IORING_SETUP_COOP_TASKRUN = c.IORING_SETUP_COOP_TASKRUN;
pub const IORING_SETUP_TASKRUN_FLAG = c.IORING_SETUP_TASKRUN_FLAG;
pub const IORING_SETUP_SQE128 = c.IORING_SETUP_SQE128;
pub const IORING_SETUP_CQE32 = c.IORING_SETUP_CQE32;
pub const IORING_SETUP_SINGLE_ISSUER = c.IORING_SETUP_SINGLE_ISSUER;
pub const IORING_SETUP_DEFER_TASKRUN = c.IORING_SETUP_DEFER_TASKRUN;
pub const IORING_SETUP_NO_MMAP = c.IORING_SETUP_NO_MMAP;
pub const IORING_SETUP_REGISTERED_FD_ONLY = c.IORING_SETUP_REGISTERED_FD_ONLY;
pub const IORING_SETUP_NO_SQARRAY = c.IORING_SETUP_NO_SQARRAY;
pub const IORING_SETUP_HYBRID_IOPOLL = c.IORING_SETUP_HYBRID_IOPOLL;

pub const IORING_SETUP_CQE_MIXED = c.IORING_SETUP_CQE_MIXED;
pub const IORING_SETUP_SQE_MIXED = c.IORING_SETUP_SQE_MIXED;
pub const IORING_SETUP_SQ_REWIND = c.IORING_SETUP_SQ_REWIND;

pub const IORING_URING_CMD_FIXED = c.IORING_URING_CMD_FIXED;
pub const IORING_URING_CMD_MASK = c.IORING_URING_CMD_MASK;
pub const IORING_FSYNC_DATASYNC = c.IORING_FSYNC_DATASYNC;

pub const IORING_TIMEOUT_ABS = c.IORING_TIMEOUT_ABS;
pub const IORING_TIMEOUT_UPDATE = c.IORING_TIMEOUT_UPDATE;
pub const IORING_TIMEOUT_BOOTTIME = c.IORING_TIMEOUT_BOOTTIME;
pub const IORING_TIMEOUT_REALTIME = c.IORING_TIMEOUT_REALTIME;
pub const IORING_LINK_TIMEOUT_UPDATE = c.IORING_LINK_TIMEOUT_UPDATE;
pub const IORING_TIMEOUT_ETIME_SUCCESS = c.IORING_TIMEOUT_ETIME_SUCCESS;
pub const IORING_TIMEOUT_MULTISHOT = c.IORING_TIMEOUT_MULTISHOT;
pub const IORING_TIMEOUT_IMMEDIATE_ARG = c.IORING_TIMEOUT_IMMEDIATE_ARG;
pub const IORING_TIMEOUT_CLOCK_MASK = c.IORING_TIMEOUT_CLOCK_MASK;
pub const IORING_TIMEOUT_UPDATE_MASK = c.IORING_TIMEOUT_UPDATE_MASK;

pub const SPLICE_F_FD_IN_FIXED = c.SPLICE_F_FD_IN_FIXED;

pub const IORING_POLL_ADD_MULTI = c.IORING_POLL_ADD_MULTI;
pub const IORING_POLL_UPDATE_EVENTS = c.IORING_POLL_UPDATE_EVENTS;
pub const IORING_POLL_UPDATE_USER_DATA = c.IORING_POLL_UPDATE_USER_DATA;
pub const IORING_POLL_ADD_LEVEL = c.IORING_POLL_ADD_LEVEL;

pub const IORING_ASYNC_CANCEL_ALL = c.IORING_ASYNC_CANCEL_ALL;
pub const IORING_ASYNC_CANCEL_FD = c.IORING_ASYNC_CANCEL_FD;
pub const IORING_ASYNC_CANCEL_ANY = c.IORING_ASYNC_CANCEL_ANY;
pub const IORING_ASYNC_CANCEL_FD_FIXED = c.IORING_ASYNC_CANCEL_FD_FIXED;
pub const IORING_ASYNC_CANCEL_USERDATA = c.IORING_ASYNC_CANCEL_USERDATA;
pub const IORING_ASYNC_CANCEL_OP = c.IORING_ASYNC_CANCEL_OP;

pub const IORING_RECVSEND_POLL_FIRST = c.IORING_RECVSEND_POLL_FIRST;
pub const IORING_RECV_MULTISHOT = c.IORING_RECV_MULTISHOT;
pub const IORING_RECVSEND_FIXED_BUF = c.IORING_RECVSEND_FIXED_BUF;
pub const IORING_SEND_ZC_REPORT_USAGE = c.IORING_SEND_ZC_REPORT_USAGE;
pub const IORING_RECVSEND_BUNDLE = c.IORING_RECVSEND_BUNDLE;
pub const IORING_SEND_VECTORIZED = c.IORING_SEND_VECTORIZED;

pub const IORING_NOTIF_USAGE_ZC_COPIED = c.IORING_NOTIF_USAGE_ZC_COPIED;
pub const IORING_ACCEPT_MULTISHOT = c.IORING_ACCEPT_MULTISHOT;
pub const IORING_ACCEPT_DONTWAIT = c.IORING_ACCEPT_DONTWAIT;
pub const IORING_ACCEPT_POLL_FIRST = c.IORING_ACCEPT_POLL_FIRST;

pub const IORING_MSG_RING_CQE_SKIP = c.IORING_MSG_RING_CQE_SKIP;
pub const IORING_MSG_RING_FLAGS_PASS = c.IORING_MSG_RING_FLAGS_PASS;
pub const IORING_FIXED_FD_NO_CLOEXEC = c.IORING_FIXED_FD_NO_CLOEXEC;
pub const IORING_NOP_INJECT_RESULT = c.IORING_NOP_INJECT_RESULT;
pub const IORING_NOP_CQE32 = c.IORING_NOP_CQE32;

pub const IORING_CQE_F_BUFFER = c.IORING_CQE_F_BUFFER;
pub const IORING_CQE_F_MORE = c.IORING_CQE_F_MORE;
pub const IORING_CQE_F_SOCK_NONEMPTY = c.IORING_CQE_F_SOCK_NONEMPTY;
pub const IORING_CQE_F_NOTIF = c.IORING_CQE_F_NOTIF;
pub const IORING_CQE_F_BUF_MORE = c.IORING_CQE_F_BUF_MORE;
pub const IORING_CQE_F_SKIP = c.IORING_CQE_F_SKIP;
pub const IORING_CQE_F_32 = c.IORING_CQE_F_32;

pub const IORING_CQE_BUFFER_SHIFT = c.IORING_CQE_BUFFER_SHIFT;

pub const IORING_OFF_SQ_RING = c.IORING_OFF_SQ_RING;
pub const IORING_OFF_CQ_RING = c.IORING_OFF_CQ_RING;
pub const IORING_OFF_SQES = c.IORING_OFF_SQES;
pub const IORING_OFF_PBUF_RING = c.IORING_OFF_PBUF_RING;
pub const IORING_OFF_PBUF_SHIFT = c.IORING_OFF_PBUF_SHIFT;
pub const IORING_OFF_MMAP_MASK = c.IORING_OFF_MMAP_MASK;

// sq_ring.flags
pub const IORING_SQ_NEED_WAKEUP = c.IORING_SQ_NEED_WAKEUP;
pub const IORING_SQ_CQ_OVERFLOW = c.IORING_SQ_CQ_OVERFLOW;
pub const IORING_SQ_TASKRUN = c.IORING_SQ_TASKRUN;

// cq_ring.flags
pub const IORING_CQ_EVENTFD_DISABLED = c.IORING_CQ_EVENTFD_DISABLED;

// io_uring_enter(2) flags
pub const IORING_ENTER_GETEVENTS = c.IORING_ENTER_GETEVENTS;
pub const IORING_ENTER_SQ_WAKEUP = c.IORING_ENTER_SQ_WAKEUP;
pub const IORING_ENTER_SQ_WAIT = c.IORING_ENTER_SQ_WAIT;
pub const IORING_ENTER_EXT_ARG = c.IORING_ENTER_EXT_ARG;
pub const IORING_ENTER_REGISTERED_RING = c.IORING_ENTER_REGISTERED_RING;
pub const IORING_ENTER_ABS_TIMER = c.IORING_ENTER_ABS_TIMER;
pub const IORING_ENTER_EXT_ARG_REG = c.IORING_ENTER_EXT_ARG_REG;
pub const IORING_ENTER_NO_IOWAIT = c.IORING_ENTER_NO_IOWAIT;

// io_uring_params.features flags
pub const IORING_FEAT_SINGLE_MMAP = c.IORING_FEAT_SINGLE_MMAP;
pub const IORING_FEAT_NODROP = c.IORING_FEAT_NODROP;
pub const IORING_FEAT_SUBMIT_STABLE = c.IORING_FEAT_SUBMIT_STABLE;
pub const IORING_FEAT_RW_CUR_POS = c.IORING_FEAT_RW_CUR_POS;
pub const IORING_FEAT_CUR_PERSONALITY = c.IORING_FEAT_CUR_PERSONALITY;
pub const IORING_FEAT_FAST_POLL = c.IORING_FEAT_FAST_POLL;
pub const IORING_FEAT_POLL_32BITS = c.IORING_FEAT_POLL_32BITS;
pub const IORING_FEAT_SQPOLL_NONFIXED = c.IORING_FEAT_SQPOLL_NONFIXED;
pub const IORING_FEAT_EXT_ARG = c.IORING_FEAT_EXT_ARG;
pub const IORING_FEAT_NATIVE_WORKERS = c.IORING_FEAT_NATIVE_WORKERS;
pub const IORING_FEAT_RSRC_TAGS = c.IORING_FEAT_RSRC_TAGS;
pub const IORING_FEAT_CQE_SKIP = c.IORING_FEAT_CQE_SKIP;
pub const IORING_FEAT_LINKED_FILE = c.IORING_FEAT_LINKED_FILE;
pub const IORING_FEAT_REG_REG_RING = c.IORING_FEAT_REG_REG_RING;
pub const IORING_FEAT_RECVSEND_BUNDLE = c.IORING_FEAT_RECVSEND_BUNDLE;
pub const IORING_FEAT_MIN_TIMEOUT = c.IORING_FEAT_MIN_TIMEOUT;
pub const IORING_FEAT_RW_ATTR = c.IORING_FEAT_RW_ATTR;
pub const IORING_FEAT_NO_IOWAIT = c.IORING_FEAT_NO_IOWAIT;

pub const IORING_MEM_REGION_TYPE_USER = c.IORING_MEM_REGION_TYPE_USER;
pub const IORING_MEM_REGION_REG_WAIT_ARG = c.IORING_MEM_REGION_REG_WAIT_ARG;

pub const IORING_RSRC_REGISTER_SPARSE = c.IORING_RSRC_REGISTER_SPARSE;

pub const IORING_REGISTER_FILES_SKIP = c.IORING_REGISTER_FILES_SKIP;
pub const IO_URING_OP_SUPPORTED = c.IO_URING_OP_SUPPORTED;

pub const IORING_REGISTER_SRC_REGISTERED = c.IORING_REGISTER_SRC_REGISTERED;
pub const IORING_REGISTER_DST_REPLACE = c.IORING_REGISTER_DST_REPLACE;

pub const IORING_REG_WAIT_TS = c.IORING_REG_WAIT_TS;
// io_uring.h END <<<

// fcntl.h
// --------
pub const RESOLVE_NO_XDEV = c.RESOLVE_NO_XDEV;
pub const RESOLVE_NO_MAGICLINKS = c.RESOLVE_NO_MAGICLINKS;
pub const RESOLVE_NO_SYMLINKS = c.RESOLVE_NO_SYMLINKS;
pub const RESOLVE_BENEATH = c.RESOLVE_BENEATH;
pub const RESOLVE_IN_ROOT = c.RESOLVE_IN_ROOT;
pub const RESOLVE_CACHED = c.RESOLVE_CACHED;

// `sync_file_range` flags for `io_uring_prep_sync_file_range`
// -----------------------------------------------------------
pub const SYNC_FILE_RANGE_WAIT_BEFORE = c.SYNC_FILE_RANGE_WAIT_BEFORE;
pub const SYNC_FILE_RANGE_WRITE = c.SYNC_FILE_RANGE_WRITE;
pub const SYNC_FILE_RANGE_WAIT_AFTER = c.SYNC_FILE_RANGE_WAIT_AFTER;

pub const O_ACCMODE = c.O_ACCMODE;
pub const O_RDONLY = c.O_RDONLY;
pub const O_WRONLY = c.O_WRONLY;
pub const O_RDWR = c.O_RDWR;

pub const O_APPEND = c.O_APPEND;
pub const O_ASYNC = c.O_ASYNC;
pub const O_CLOEXEC = c.O_CLOEXEC;
pub const O_CREAT = c.O_CREAT;
// ...
pub const O_DIRECT = c.__O_DIRECT;
pub const O_DIRECTORY = c.O_DIRECTORY;
pub const O_DSYNC = c.O_DSYNC;
pub const O_EXCL = c.O_EXCL;
pub const O_LARGEFILE = c.__O_LARGEFILE;
pub const O_NOATIME = c.__O_NOATIME;
pub const O_NOCTTY = c.O_NOCTTY;
pub const O_NOFOLLOW = c.O_NOFOLLOW;
pub const O_NONBLOCK = c.O_NONBLOCK; // 'O_NDELA;
pub const O_PATH = c.__O_PATH;
// ...
pub const O_SYNC = c.O_SYNC;
pub const O_TMPFILE = c.__O_TMPFILE; // must be specified with `O_RDWR` | `O_WRONLY`. `O_EXCL` (optiona;
pub const O_TRUNC = c.O_TRUNC;

// flags for `renameat2`.
pub const RENAME_NOREPLACE = c.RENAME_NOREPLACE;
pub const RENAME_EXCHANGE = c.RENAME_EXCHANGE;
pub const RENAME_WHITEOUT = c.RENAME_WHITEOUT;

// AT_* flags
pub const AT_FDCWD = c.AT_FDCWD;
pub const AT_SYMLINK_FOLLOW = c.AT_SYMLINK_FOLLOW;
pub const AT_SYMLINK_NOFOLLOW = c.AT_SYMLINK_NOFOLLOW;
pub const AT_REMOVEDIR = c.AT_REMOVEDIR;
pub const AT_NO_AUTOMOUNT = c.AT_NO_AUTOMOUNT;
pub const AT_EMPTY_PATH = c.AT_EMPTY_PATH;
pub const AT_RECURSIVE = c.AT_RECURSIVE;

// splice flags
pub const SPLICE_F_MOVE = c.SPLICE_F_MOVE;
pub const SPLICE_F_NONBLOCK = c.SPLICE_F_NONBLOCK;
pub const SPLICE_F_MORE = c.SPLICE_F_MORE;
pub const SPLICE_F_GIFT = c.SPLICE_F_GIFT;

// `fallocate` mode
pub const FALLOC_FL_KEEP_SIZE = c.FALLOC_FL_KEEP_SIZE;
pub const FALLOC_FL_PUNCH_HOLE = c.FALLOC_FL_PUNCH_HOLE;
pub const FALLOC_FL_NO_HIDE_STALE = c.FALLOC_FL_NO_HIDE_STALE;
pub const FALLOC_FL_COLLAPSE_RANGE = c.FALLOC_FL_COLLAPSE_RANGE;
pub const FALLOC_FL_ZERO_RANGE = c.FALLOC_FL_ZERO_RANGE;
pub const FALLOC_FL_INSERT_RANGE = c.FALLOC_FL_INSERT_RANGE;
pub const FALLOC_FL_UNSHARE_RANGE = c.FALLOC_FL_UNSHARE_RANGE;

pub const RWF_APPEND = c.RWF_APPEND;
pub const RWF_DSYNC = c.RWF_DSYNC;
pub const RWF_HIPRI = c.RWF_HIPRI;
pub const RWF_NOWAIT = c.RWF_NOWAIT;
pub const RWF_SYNC = c.RWF_SYNC;
pub const RWF_NOAPPEND = if (@hasDecl(c, "RWF_NOAPPEND")) c.RWF_NOAPPEND else 0;
pub const RWF_ATOMIC = if (@hasDecl(c, "RWF_ATOMIC")) c.RWF_ATOMIC else 0;
